"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""


def fibonacci():

    # Start fibonacci list with first 2 digits
    fibonacci_list = [1, 2]
    sum_fibonacci_nums = 2

    for i in range(50):
        sum = fibonacci_list[i] + fibonacci_list[i+1]
        if sum <= 4000000:
            fibonacci_list.append(sum)
            if sum % 2 == 0:
                sum_fibonacci_nums += sum
                print(sum)
        else:
            break

    return sum_fibonacci_nums


if __name__ == "__main__":
    fibonacci()
